<?php

use Sulde\Service\Common\Common;

$title = 'User profile';
$this->headTitle($title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('user-dashboard')?>">Home</a></li>
    <li class="active">Dashboard</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title" style="padding-bottom: 20px;">
    <span id="btnModal" style="width: 30px" class="input-group-addon add-on">
        <span class="glyphicon glyphicon-calendar"></span> <?=$this->strReportDate?>
    </span>
</div>

<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body" style="text-align: center">
                    <div style="text-align: center"><span class="fa fa-signal" style="font-size: 100pt; color: #2db3dc"></span></div>
                    <h4>DOANH THU</h4>
                    <div style="color: #2db3dc; font-size: 18pt; font-weight: bold"><?=Common::formatMoney($this->totalRevenue)?></div>
                    <div><b>Tổng đơn hàng: <?=$this->orderNumber?></b></div>
                    <div style="text-align: left; padding-top: 30px"><b>Doanh thu:</b> Bằng tổng giá trị các đơn hàng đã thanh toán.</div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <!-- START DONUT CHART -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="morris-donut-cat" style="height: 300px;"></div>
                </div>
            </div>
            <!-- END DONUT CHART -->
        </div>

        <div class="col-md-4">
            <!-- START LINE CHART -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="morris-line-example" style="height: 300px;"></div>
                </div>
            </div>
            <!-- END LINE CHART -->
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade bottom" id="modalDate" tabindex="-1" role="dialog" aria-labelledby="modalDate" aria-hidden="true">
    <input id="local" value="" type="hidden">
    <div class="modal-dialog modal-bottom" role="document">
        <div class="modal-content">
            <div class="row" style="padding: 10px">
                <label class="col-md-2 control-label">Từ ngày</label>
                <div class="col-md-4">
                    <div class="input-group">
                        <input type="text" class="form-control" value="<?=date("Y-m-d", strtotime("first day of this month"))?>" id="fdate" data-date-format="yyyy-mm-dd" data-date-viewmode="months">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>
                <label class="col-md-2 control-label">Đến ngày</label>
                <div class="col-md-4">
                    <div class="input-group">
                        <input type="text" class="form-control" value="<?=date("Y-m-d")?>" id="tdate" data-date-format="yyyy-mm-dd" >
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>
                <div class="col-md-12" style="padding: 10px">
                    <button id="btnSubmit" class="btn btn-success">Xem báo cáo</button>
                </div>
            </div>


        </div>
    </div>
</div>

<script type="text/javascript" src="/joli/js/plugins/morris/raphael-min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/morris/morris.min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/morris/morris.min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/bootstrap/bootstrap-datepicker.js"></script>


<script>
    $("#tdate,#fdate").datepicker();
    month = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

    $( document ).ready(function() {
        $('#btnModal').click(function(){
            $('#modalDate').modal('show')
        })
        $('#btnSubmit').click(function(){
            var url='<?=$this->url('user-dashboard',['action'=>'report'])?>?fd='+$('#fdate').val()+'&td='+$('#tdate').val();
            location.href=url;
        })
    });

    var morrisCharts = function(){
        Morris.Donut({
            element: 'morris-donut-cat',
            data: [
                <?php
                foreach ($this->arrRevenueByProductCat as $k=>$v){
                    echo '{label: "'.$v['name'].'", value: '.$v['revenue'].'},';
                }
                ?>
            ],
            colors: ['#95B75D', '#1caf9a', '#FEA223']
        });

        Morris.Line({
            element: 'morris-line-example',
            data: [
                <?php
                foreach ($this->arrLine as $k=>$v){
                    echo "{ y: '".$k."', revenue: ".$v['revenue']." },";
                }
                ?>
            ],
            xkey: 'y',
            ykeys: ['revenue'],
            labels: ['Doanh thu', 'Lợi nhuận'],
            resize: true,
            lineColors: ['#33414E', '#95B75D'],
            xLabelFormat: function(d) {
                return d.getDate()+'/'+month[d.getMonth()];
            }
        });
    }();
</script>