
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->headTitle('NPP Anh Vũ')->setSeparator(' - ')->setAutoEscape(true)?>
    <?=$this->headTitle($this->privilege['name']);?>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://adminlte.io/themes/v3/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/vendor/adminlte/dist/css/adminlte.min.css">

    <!-- jQuery -->
    <script src="/vendor/adminlte/plugins/jquery/jquery-3.7.1.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/vendor/adminlte/plugins/bootstrap/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="/vendor/adminlte/plugins/bootstrap/bootstrap-4.min.css">

    <script src="/vendor/adminlte/plugins/sweetalert2/js/sweetalert2.min.js"></script>
    <script>let Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 5000
    });</script>

    <!-- AdminLTE App -->
    <script src="/vendor/adminlte/dist/js/adminlte.min.js"></script>

    <!--  Datatables  -->
    <link href="/vendor/adminlte/plugins/datatables/2.3.5/css/datatables.min.css" rel="stylesheet" crossorigin="anonymous">
    <script src="/vendor/adminlte/plugins/datatables/2.3.5/js/datatables.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/vendor/adminlte/plugins/datatables/2.3.5/css/responsive.dataTables.min.css">
    <script src="/vendor/adminlte/plugins/datatables/2.3.5/js/dataTables.responsive.min.js"></script>
    <script src="/vendor/adminlte/plugins/datatables/2.3.5/js/dataTables.select.min.js"></script>


    <link rel="stylesheet" type="text/css" id="theme" href="/theme/css/sulde.css"/>
    <link href="/vendor/jquery/waitMe/waitMe.css" rel="stylesheet">
    <script src="/vendor/jquery/waitMe/waitMe.js"></script>
    <script type="text/javascript" src="/theme/js/admin.js"></script>
    <script src="/vendor/adminlte/plugins/mustache/mustache.min.js"></script>
</head>
<body class="layout-fixed sidebar-expand-lg sidebar-mini sidebar-collapse bg-body-tertiary">
<!-- Site wrapper -->
<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="../../index3.html" class="nav-link">Home</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contact</a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Navbar Search -->
            <li class="nav-item">
                <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                    <i class="fas fa-search"></i>
                </a>
                <div class="navbar-search-block">
                    <form class="form-inline">
                        <div class="input-group input-group-sm">
                            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-navbar" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>

            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments"></i>
                    <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="/vendor/adminlte/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Brad Diesel
                                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">Call me whenever you can...</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="/vendor/adminlte/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    John Pierce
                                    <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">I got your message bro</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="/vendor/adminlte/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Nora Silvester
                                    <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">The subject goes here</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-item dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout" role="button">
                    <i class="fas fa-sign-out-alt"></i>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="../../index3.html" class="brand-link">
            <img src="/vendor/adminlte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">AdminLTE 3</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="/vendor/adminlte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">Alexander Pierce</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item">
                        <a href="https://adminlte.io/docs/3.1/" target="_blank" class="nav-link">
                            <i class="nav-icon fas fa-file"></i>
                            <p>
                                Documentation
                                <span class="right badge badge-danger">New</span>
                            </p>
                        </a>
                    </li>

                    <?php
                    $parents=$this->roles[0];

                    usort($parents, function($a, $b) {
                        return @$a['menu_sort'] <=> @$b['menu_sort']; // toán tử so sánh ba chiều (PHP 7+)
                    });
                    $selectedId=$this->privilege['id'];
                    foreach ( $parents as $parent){
                        //hien thi chuc nang tren menu
                        if($parent['menu_display']==1){
                            $children = @$this->roles[$parent['id']];
                            if($children){
                                echo '<li class="nav-item">';
                                echo '<a href="#" class="nav-link"><i class="nav-icon '.$parent['icon'].'"></i> <p>'.$parent['name'].'<i class="fas fa-angle-left right"></i></p></a>';
                                echo '<ul class="nav nav-treeview">';
                                foreach ( $children as $childrenItem) {
                                    if($childrenItem['menu_display']==1){
                                        if($childrenItem['id']==$selectedId) $active='active'; else $active='';
                                        $url= ($childrenItem['action']=='index')?$this->url($childrenItem['url']):$this->url($childrenItem['url'],['action'=>$childrenItem['action']]);
                                        echo '<li class="nav-item">';
                                        echo '<a href="'.$url.'" class="nav-link '.$active.'"><i class="nav-icon '.$childrenItem['icon'].'"></i><p>' . $childrenItem['name'] . '</p></a>';
                                        echo '</li>';
                                    }
                                }
                                echo '</ul>';
                                echo '</li>';
                            }else{
                                $url= ($parent['action']=='index')?$this->url($parent['url']):$this->url($parent['url'],['action'=>$parent['action']]);
                                echo '<li class="nav-item">';
                                echo '<a href="'.$url.'" class="nav-link"><i class="nav-icon '.$parent['icon'].'"></i><p>'.$parent['name'].'</p></a>';
                                echo '</li>';
                            }
                        }
                    }
                    ?>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 page-title"><?=$this->privilege['name']?></h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <?php
                            foreach ($this->breadcrumb as $item){
                                if(@$item['active']){
                                    echo '<li class="breadcrumb-item active">'.$item['name'].'</li>';
                                }else{
                                    $url= ($item['action']=='index')?$this->url($item['url']):$this->url($item['url'],['action'=>$item['action']]);
                                    echo '<li class="breadcrumb-item"><a href="'.$url.'">'.$item['name'].'</a></li>';
                                }
                            }
                            ?>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <?= $this->content ?>
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
            <b>Version</b> 3.2.0
        </div>
        <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
</body>
</html>
