<?= $this->doctype() ?>

<html lang="en" class="body-full-height">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('NPP Anh Vũ')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/favicon.png'])?>


    <!-- CSS INCLUDE -->
    <link rel="stylesheet" type="text/css" id="theme" href="/joli/css/theme-default.css"/>

</head>
<body>
<?= $this->content ?>
</body>
</html>
