<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('NPP Anh Vũ')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,viewport-fit=cover">
    <?= $this->headMeta()
//        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/favicon.png'])?>


    <!-- CSS INCLUDE -->
    <link rel="stylesheet" type="text/css" id="theme" href="/joli/css/theme-default.css"/>
    <link rel="stylesheet" type="text/css" id="theme" href="/css/sulde.css"/>

    <!-- START SCRIPTS -->
    <!-- START PLUGINS -->
    <script type="text/javascript" src="/joli/js/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/joli/js/plugins/jquery/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/joli/js/plugins/bootstrap/bootstrap.min.js"></script>
    <!-- END PLUGINS -->

    <!-- THIS PAGE PLUGINS -->
    <script type="text/javascript" src="/joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
    <!-- END PAGE PLUGINS -->

    <!-- START TEMPLATE -->
    <script type="text/javascript" src="/joli/js/plugins.js"></script>
    <script type="text/javascript" src="/joli/js/actions.js"></script>
    <!-- START NOTY -->
    <script type='text/javascript' src='/joli/js/plugins/noty/jquery.noty.js'></script>
    <script type='text/javascript' src='/joli/js/plugins/noty/layouts/topRight.js'></script>
    <script type='text/javascript' src='/joli/js/plugins/noty/themes/default.js'></script>
<!--
    <script type="text/javascript" src="/joli/js/plugins/datatables/jquery.dataTables.2.1.8.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/css/dataTables.dataTables.css"/>
-->
    <link href="/js/datatables/2.3.5/datatables.min.css" rel="stylesheet" crossorigin="anonymous">

    <script src="/js/datatables/2.3.5/datatables.min.js" crossorigin="anonymous"></script>

    <link href="/vendor/jquery/waitMe/waitMe.css" rel="stylesheet">
    <script src="/vendor/jquery/waitMe/waitMe.js"></script>
    <script type="text/javascript" src="/js/admin.js"></script>
    <script src="/js/mustache.min.js"></script>
    <!-- END TEMPLATE -->
    <!-- END SCRIPTS -->

</head>
<body>
<!-- START PAGE CONTAINER -->
<div class="page-container page-navigation page-navigation-toggled page-container-wide">

    <!-- START PAGE SIDEBAR -->
    <div class="page-sidebar">
        <!-- START X-NAVIGATION -->
        <ul class="x-navigation">
            <li class="xn-logo">
                <a href="<?=$this->url('admin-dashboard')?>">NPP Anh Vũ</a>
                <a href="#" class="x-navigation-control"></a>
            </li>
            <?php
            $avatar = "/img/users/avatar.png";
            if($this->authIdentity->getAvatar()){
                $avatar = $this->authIdentity->getAvatar();
            }
            ?>
            <li class="xn-profile">
                <a href="#" class="profile-mini">
                    <img src="<?=$avatar?>" alt="<?=$this->authIdentity->getFullname();?>"/>
                </a>
                <div class="profile">
                    <div class="profile-image">
                        <img src="<?=$avatar?>" alt="<?=$this->authIdentity->getFullname();?>"/>
                    </div>
                    <div class="profile-data">
                        <div class="profile-data-name"><?=$this->authIdentity->getFullname();?></div>
                        <div class="profile-data-title"><?=ucfirst($this->authIdentity->getRole());?></div>
                    </div>
                    <div class="profile-controls">
                        <a href="<?=$this->url('user-admin',['action'=>'profile'])?>" class="profile-control-left"><span class="fa fa-info"></span></a>
                        <a href="#" class="profile-control-right"><span class="fa fa-envelope"></span></a>
                    </div>
                </div>
            </li>
            <li class="xn-title">Navigation</li>
            <?php
            $parents=$this->roles[0];

            usort($parents, function($a, $b) {
                return @$a['menu_sort'] <=> @$b['menu_sort']; // toán tử so sánh ba chiều (PHP 7+)
            });

            foreach ( $parents as $parent){
                //hien thi chuc nang tren menu
                if($parent['menu_display']==1){
                    $children = @$this->roles[$parent['id']];
                    if($children){
                        echo '<li class="xn-openable">';
                        echo '<a href="#"><span class="'.$parent['icon'].'"></span> <span class="xn-text">'.$parent['name'].'</span></a>';
                        echo '<ul>';
                        foreach ( $children as $childrenItem) {
                            if($childrenItem['menu_display']==1){
                                $url= ($childrenItem['action']=='index')?$this->url($childrenItem['url']):$this->url($childrenItem['url'],['action'=>$childrenItem['action']]);
                                echo '<li>';
                                echo '<a href="'.$url.'"><span class="'.$childrenItem['icon'].'"></span>' . $childrenItem['name'] . '</a>';
                                echo '</li>';
                            }
                        }
                        echo '</ul>';
                        echo '</li>';
                    }else{
                        $url= ($parent['action']=='index')?$this->url($parent['url']):$this->url($parent['url'],['action'=>$parent['action']]);
                        echo '<li>';
                        echo '<a href="'.$url.'"><span class="'.$parent['icon'].'"></span> <span class="xn-text">'.$parent['name'].'</span></a>';
                        echo '</li>';
                    }
                }
            }
            ?>
        </ul>
        <!-- END X-NAVIGATION -->
    </div>
    <!-- END PAGE SIDEBAR -->


    <!-- PAGE CONTENT -->
    <div class="page-content">

        <!-- START X-NAVIGATION VERTICAL -->
        <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
            <!-- TOGGLE NAVIGATION -->
            <li class="xn-icon-button">
                <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
            </li>
            <!-- END TOGGLE NAVIGATION -->
            <!-- SEARCH -->
            <li class="xn-search">
                <form role="form">
                    <input type="text" name="search" placeholder="Search..."/>
                </form>
            </li>
            <!-- END SEARCH -->
            <!-- SIGN OUT -->
            <li class="xn-icon-button pull-right">
                <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span></a>
            </li>
            <!-- END SIGN OUT -->
            <!-- MESSAGES -->
            <li class="xn-icon-button pull-right">
                <a href="#"><span class="fa fa-comments"></span></a>
                <div id="messageInformer" class="informer informer-danger"></div>
                <div class="panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging">
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="fa fa-comments"></span> Tin nhắn</h3>
                        <div class="pull-right">
                            <span id="messageActive" class="label label-danger"></span>
                        </div>
                    </div>
                    <div class="panel-body list-group list-group-contacts scroll" style="height: 200px;">

                    </div>
                    <div class="panel-footer text-center">
                        <a href="#">Show all messages</a>
                    </div>
                </div>
            </li>
            <!-- END MESSAGES -->
            <!-- TASKS -->
            <li class="xn-icon-button pull-right">
                <a href="#"><span class="fa fa-tasks"></span></a>
                <div id="activityInformer" class="informer informer-warning"></div>
                <div class="panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging">
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="fa fa-tasks"></span> Activity</h3>
                        <div class="pull-right">
                            <span id="activityActive" class="label label-warning"></span>
                        </div>
                    </div>
                    <div id="activityTask" class="panel-body list-group scroll" style="height: 200px;"></div>
                    <div class="panel-footer text-center">
                        <a href="#">Show all tasks</a>
                    </div>
                </div>
            </li>
            <!-- END TASKS -->
        </ul>
        <!-- END X-NAVIGATION VERTICAL -->

        <!-- START BREADCRUMB -->
        <ul class="breadcrumb">
        <?php
        foreach ($this->breadcrumb as $item){
            if(@$item['active']){
                echo '<li class="active">'.$item['name'].'</li>';
            }else{
                $url= ($item['action']=='index')?$this->url($item['url']):$this->url($item['url'],['action'=>$item['action']]);
                echo '<li><a href="'.$url.'">'.$item['name'].'</a></li>';
            }
        }
        ?>
        </ul>
        <!-- END BREADCRUMB -->


        <?= $this->content ?>

    </div>
    <!-- END PAGE CONTENT -->

</div>
<!-- END PAGE CONTAINER -->


<!-- MESSAGE BOX-->
<div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
            <div class="mb-content">
                <p>Are you sure you want to log out?</p>
                <p>Press No if you want to continue work. Press Yes to logout current user.</p>
            </div>
            <div class="mb-footer">
                <div class="pull-right">
                    <a href="/logout" class="btn btn-success btn-lg">Yes</a>
                    <button class="btn btn-default btn-lg mb-control-close">No</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END MESSAGE BOX-->

<!-- MESSAGE BOX CONFIRM DELETE DATA-->
<div class="message-box message-box-warning animated fadeIn" data-sound="alert" id="mb-remove-row">
    <div class="mb-container">
        <div class="mb-middle">
            <div class="mb-title"><span class="fa fa-times"></span> <?=$this->translate('Remove')?> <strong><?=$this->translate('Data')?></strong> ?</div>
            <div class="mb-content">
                <p><?=$this->translate('Are you sure you want to remove this row?')?></p>
                <p><?=$this->translate('Press Yes if you sure.')?></p>
            </div>
            <div class="mb-footer">
                <div class="pull-right">
                    <button class="btn btn-danger btn-lg mb-control-yes">Yes</button>
                    <button class="btn btn-success btn-lg mb-control-close">No</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END MESSAGE BOX-->

<!-- START PRELOADS -->
<audio id="audio-alert" src="/joli/audio/alert.mp3" preload="auto"></audio>
<audio id="audio-fail" src="/joli/audio/fail.mp3" preload="auto"></audio>
<style>
    .actTitle{font-weight: bold};
</style>
<!-- END PRELOADS -->
<script>
    $( document ).ready(function() {
    })
</script>

</body>
</html>
