<?php
/**
 * Copyright (c) 2019.  Sulde JSC
 * Created by   : TruongHM
 * Created date: 7/15/19 3:24 PM
 *
 */

$title = "Add new user";
$this->headTitle($title);
$form->prepare();
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('user-admin')?>">User list</a></li>
    <li class="active">Add new user</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> <?=$this->escapeHtml($title)?></h2>
</div>

<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if(count($this->flashMessenger()->getErrorMessages())>0){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->getErrorMessages()[0]?>
                </div>
                <?php
            }
            ?>
        </div>
        <div class="col-md-12">
            <div class="panel panel-success">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-7 col-md-offset-2">
                        <?=$this->form()->openTag($form)?>
                        <div class="form-group">
                            <?=$this->formLabel($form->get('mobile'));?>
                            <div class="col-md-9">
                                <?php
                                echo $this->formElement($form->get('mobile'));
                                echo $this->formElementErrors($form->get('mobile'));
                                ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <?=$this->formLabel($form->get('email'));?>
                            <div class="col-md-9">
                                <?php
                                echo $this->formElement($form->get('email'));
                                echo $this->formElementErrors($form->get('email'));
                                ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <?=$this->formLabel($form->get('fullname'));?>
                            <div class="col-md-9">
                                <?php
                                echo $this->formElement($form->get('fullname'));
                                echo $this->formElementErrors($form->get('fullname'));
                                ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <?=$this->formLabel($form->get('birthdate'));?>
                            <div class="col-md-9">
                                <?php
                                echo $this->formElement($form->get('birthdate'));
                                echo $this->formElementErrors($form->get('birthdate'));
                                ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <?=$this->formLabel($form->get('password'));?>
                            <div class="col-md-9">
                                <?php
                                echo $this->formElement($form->get('password'));
                                echo $this->formElementErrors($form->get('password'));
                                ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?=$this->formLabel($form->get('confirm_password'));?>
                            <div class="col-md-9">
                                <?php
                                echo $this->formElement($form->get('confirm_password'));
                                echo $this->formElementErrors($form->get('confirm_password'));
                                ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-7 col-md-offset-3">
                                <?=$this->formElement($form->get('btnSubmit'));?>
                            </div>
                        </div>
                        <?=$this->form()->closeTag()?>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>