<?php
$title = "Change password";
$this->headTitle("Change password");
$form->prepare();
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('user-admin')?>">User list</a></li>
    <li class="active">Change password</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> <?=$this->escapeHtml($title)?></h2>
</div>
<div class="page-content-wrap">
    <div class="panel panel-success">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <?php
                    if(count($this->flashMessenger()->getErrorMessages())>0){
                        ?>
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                            <?=$this->flashMessenger()->getErrorMessages()[0]?>
                        </div>
                        <?php
                    }
                    ?>
                </div>
                <div class="col-md-5 col-md-offset-3">
                    <?=$this->form()->openTag($form)?>

                    <!--<div class="form-group">
                        <?/*=$this->formLabel($form->get('old_pw'));*/?>
                        <div class="col-md-6">
                            <?php
/*                            echo $this->formElement($form->get('old_pw'));
                            echo $this->formElementErrors($form->get('old_pw'));
                            */?>
                        </div>
                    </div>-->
                    <div class="form-group">
                        <?=$this->formLabel($form->get('new_pw'));?>
                        <div class="col-md-6">
                            <?php
                            echo $this->formElement($form->get('new_pw'));
                            echo $this->formElementErrors($form->get('new_pw'));
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?=$this->formLabel($form->get('confirm_new_pw'));?>
                        <div class="col-md-6">
                            <?php
                            echo $this->formElement($form->get('confirm_new_pw'));
                            echo $this->formElementErrors($form->get('confirm_new_pw'));
                            ?>
                        </div>
                    </div>
                    <?php echo $this->formElement($form->get('csrf'));?>
                    <div class="form-group">
                        <div class="col-md-7 col-md-offset-4">
                            <?=$this->formElement($form->get('submit'));?>
                        </div>
                    </div>
                    <?=$this->form()->closeTag()?>
                </div>
            </div>
        </div>
    </div>
</div>