<?php
$title = "Đặc quyền riêng cho thành viên";
$this->headTitle($title);
use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('user-admin')?>"> User list</a></li>
    <li class="active"><?=$title?></li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->

<!-- Required Stylesheets -->
<link href="/vendor/hummingbird-v.3.0.5/hummingbird-treeview.min.css" rel="stylesheet">

<!-- Required Javascript -->
<script src="/vendor/hummingbird-v.3.0.5/hummingbird-treeview.min.js"></script>

<div class="page-content-wrap">
    <div class="content-frame">
        <div class="content-frame-top">
            <div class="page-title">
                <h2><span class="fa fa-arrow-circle-o-left"></span> <?=$title?></h2>
            </div>
            <div class="pull-right">
                <button id="btnSave" class="btn btn-default"><span class="fa fa-save"></span> Save</button>
                <button class="btn btn-default content-frame-left-toggle"><span class="fa fa-bars"></span></button>
            </div>

        </div>
        <!-- START CONTENT FRAME LEFT -->
        <div class="content-frame-left">
            <div class="panel panel-default">
                <div class="panel-body profile" style="background: url('/img/bag-van-da.jpg') center center no-repeat;">
                    <div class="profile-image">
                        <img src="<?=($this->user->getAvatar()?$this->user->getAvatar():'/img/users/avatar.png')?>" />
                    </div>
                    <div class="profile-data">
                        <div class="profile-data-name"><?=$this->user->getUsername()?></div>
                        <div class="profile-data-title" style="color: #FFF;"><?=$this->user->getFullname()?></div>
                        <div class="profile-data-title" style="color: #FFF;">Mobile: <?=$this->user->getMobile()?></div>
                    </div>
                    <div class="profile-controls">
                        <a href="<?=$this->url('user-admin',['action'=>'profile'])?>" class="profile-control-left twitter"><span class="fa fa-info"></span></a>
                        <a href="#" class="profile-control-right facebook"><span class="fa fa-envelope"></span></a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <button class="btn btn-info btn-rounded btn-block"><span class="fa fa-cog"></span> <?=$this->user->getRole()?></button>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-primary btn-rounded btn-block"><span class="fa fa-check"></span> <?=($this->user->getStatus()?'Active':'No Active')?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END CONTENT FRAME LEFT -->
        <!-- START CONTENT FRAME BODY -->
        <div class="content-frame-body">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="treeview_container" class="hummingbird-treeview">
                        <ul id="treeview" class="hummingbird-base">
                            <li>
                                <i class="fa fa-minus"></i>
                                <label><input id="xnode-0" data-id="custom-0" type="checkbox" /> All privileges</label>
                                <ul style="display: block;">
                                    <?php
                                    foreach ($this->roleGroup as $key =>$items){
                                        echo '<li>';
                                        echo '<i class="fa fa-plus"></i> ';
                                        echo '<label><input  id="'.$key.'" data-id="'.$key.'" type="checkbox" /> '.$key.' </label>';

                                        if(@count($items>0)){
                                            echo '<ul>';
                                            foreach ($items as $k =>$privilege){
                                                echo '<li>';
                                                echo '<label><input class="hummingbird-end-node" value="'.$privilege->getId().'" id="'.$privilege->getId().'" data-id="'.$privilege->getId().'" type="checkbox" /> '.$privilege->getName().'</label>';
                                                echo '</li>';
                                            }
                                            echo '</ul>';
                                        }

                                        echo '</li>';
                                    }
                                    ?>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- END CONTENT FRAME BODY -->
    </div>
</div>
<script>
    $( document ).ready(function() {
        $("#treeview").hummingbird();
        <?php
        $checked=array();
        $disablePrivilegeCheck=array();

        if($this->role)
            foreach ($this->role->getPrivileges() as $privileges)
                $disablePrivilegeCheck[]=$privileges->getId();
        if($this->user->getPrivatePrivileges())
            foreach ($this->user->getPrivatePrivileges() as $privileges)
                $checked[]=$privileges->getId();
        ?>

        //disable all privilege off role
        $("#treeview").hummingbird("disableNode",{sel:"id",vals:<?=json_encode($disablePrivilegeCheck)?>,expandParents:false})

        //checked privilege check box
        $("#treeview").hummingbird("checkNode",{sel:"id",vals:<?=json_encode($checked)?>,expandParents:false})

        $('#btnSave').click(function(){
            // console.log('save clicked!');
            let checked = {"id" : [], "dataid" : [], "text" : []};
            //get all checked nodes
            $("#treeview").hummingbird("getChecked",{list:checked,onlyEndNodes:true});
            // console.log(checked.id);

            run_waitMe();
            $.ajax({
                headers: {Accept: "application/json; charset=utf-8"},
                method: "POST",
                url: '<?=$this->url('user-admin',['action'=>'update-privileges'])?>',
                data: {uid:<?=$this->user->getId()?>,data:checked.id}
            }).done(function (response) {
                if(response.status){
                    noty({text: response.message, layout: 'topRight', type: 'success',timeout: 8000});
                }
                else{
                    noty({text: response.message, layout: 'topRight', type: 'error',timeout: 4000});
                }
                stop_waitMe();
            });
        })
    });
</script>