<?php
$title = "User list";
$this->headTitle($title);

$form=$this->form;
$form->setAttributes([
    'enctype'=>'multipart/form-data'
]);

$form->prepare();

use Sulde\Service\Common\Common;
use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger; ?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li class="active">User list</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)){
                ?>
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)?>
                </div>
                <?php
            }
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body profile bg-success">
                    <div class="profile-image">
                        <?php
                        if($this->user->getAvatar()) $avatarSource= $this->user->getAvatar();
                        else $avatarSource = '/img/users/avatar.png'
                        ?>
                        <img src="<?=$avatarSource?>" alt="<?=$this->user->getFullname()?>">
                    </div>
                    <div class="profile-data">
                        <div class="profile-data-name"><?=$this->user->getFullname()?></div>
                        <div class="profile-data-title"><?=ucfirst($this->user->getRole())?></div>
                    </div>
                    <div class="profile-controls">
                        <a href="#" class="profile-control-left"><span class="fa fa-info"></span></a>
                        <a href="#" class="profile-control-right"><span class="fa fa-phone"></span></a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="contact-info">
                        <?php
                        $email = $this->user->getEmail();
                        if(!$email) $email='-/-';

                        $status = $this->user->getStatus();
                        if($status==1) $status='<span class="label label-success label-form">Active</span>';
                        else $status = '<span class="label label-danger">Unactive</span>';
                        ?>
                        <p><b><?=$this->translate('Mobile')?></b>: <?=$this->user->getMobile()?></p>
                        <p><b>Email</b>: <?=$email?></p>
                        <p><b><?=$this->translate('Status')?></b>: <?=$status?></p>
                        <p><b><?=$this->translate('Created date')?></b>: <?=Common::formatDateTime($this->user->getCreatedDate())?></p>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-8">
            <?=$this->form()->openTag($form)?>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Đăng nhập gần nhất:</label>
                        <div class="col-md-9">
                            <?=Common::getTimeAgo($this->user->getLoginDate())?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?=$this->formLabel($form->get('fullname'));?>
                        <div class="col-md-9">
                            <?php
                            echo $this->formElement($form->get('fullname'));
                            echo $this->formElementErrors($form->get('fullname'));
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label"><?=$this->translate('Upload avatar')?>:</label>
                        <div class="col-md-9">
                            <input type="file" name="file-avatar" id="file-avatar"/>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-9">
                        <?=$this->formElement($form->get('btnSubmit'));?> <span class="label label-success label-form"><?=$this->message?></span>
                    </div>
                </div>
            </div>
            <?=$this->form()->closeTag()?>
        </div>
    </div>
</div>
<script type='text/javascript' src='/joli/js/plugins/icheck/icheck.min.js'></script>
<script type="text/javascript" src="/joli/js/plugins/fileinput/fileinput.min.js"></script>
<script>
    $(function() {
        $("#file-avatar").fileinput({
            showUpload: false,
            showCaption: false,
            showRemove: false, // hide remove button
            uploadAsync: true,
            browseClass: "btn btn-danger",
            allowedFileExtensions: ['jpg', 'png', 'gif']
        });
    });
</script>