<?php

use Sulde\Service\Common\Common;
use Sulde\Service\Common\Define;

$title = "Chi tiết phiếu thanh toán";
$this->headTitle($title);
?>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card card-default">
                    <div class="card-header">
                        <div class="user-block">
                            <img class="img-circle" src="/assets/images/avatar.png">
                            <span class="username"><a href="#"><?=$this->payment->getSupplier()->getShortName()?$this->payment->getSupplier()->getShortName():$this->payment->getSupplier()->getName()?></a></span>
                            <span class="description"><?=$this->payment->getSupplier()->getAddress()?></span>
                        </div>
                        <div class="card-tools">
                            <?php
                            if($this->payment->getStatus()!=Define::STATUS_PAID){
                                ?>

                                <div class="btn-group">
                                    <button type="button" class="btn btn-info btn-payment-confirm">
                                        <i class="fa fa-solid fa-gavel"></i>
                                        Xác nhận Thanh toán
                                    </button>
                                    <button type="button" class="btn btn-info dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    <div class="dropdown-menu" role="menu" style="">
                                        <button class="dropdown-item" id="btn-delete-payment">
                                            <i class="fas fa-trash-alt"></i>
                                            Xoá phiếu thanh toán
                                        </button>
                                    </div>
                                </div>
                            <?php }else{
                                ?>
                                <button type="button" class="btn btn-danger btn-payment-cancel">
                                    <i class="fa far fa-power-off"></i>
                                    Huỷ thanh toán
                                </button>
                            <?php
                            }?>
                        </div>

                    </div>
                    <div class="card-body">
                        <?php
                        $debtLedgerInfo=$this->payment->getSupplier()->getDebtLedgerInfo();
                        $accountPayable=0;
                        $accountsReceivable=0;
                        if($debtLedgerInfo['account_payable']>0) $accountPayable=$debtLedgerInfo['account_payable'];
                        else $accountsReceivable=abs($debtLedgerInfo['account_payable']);
                        ?>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="small-box bg-info">
                                    <div class="inner">
                                        <h3 class="paid-total"><?=Common::formatMoney($accountPayable)?></h3>
                                        <h5>Công nợ phải trả</h5>
                                        <i class="fas fa-hand-point-right"></i> <small>Mua hàng từ nhà cung cấp</small>
                                    </div>
                                    <div class="icon">
                                        <i class="fas fa-dollar-sign"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="small-box bg-warning">
                                    <div class="inner">
                                        <h3 class="purchase-return-total"><?=Common::formatMoney($accountsReceivable)?></h3>
                                        <h5>Công nợ phải thu</h5>
                                        <i class="fas fa-hand-point-right"></i> <small>Phải thu từ NCC (Trả thàng + Thanh toán > Nhập)</small>
                                    </div>
                                    <div class="icon">
                                        <i class="fas fa-hand-holding-usd"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th style="width:30%">Nhà cung cấp:</th>
                                    <td>
                                        <span class="highlight"><?=$this->payment->getSupplier()->getName()?></span>
                                        <br><small><i><?=$this->payment->getSupplier()->getAddress()?></i></small>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Số tiền:</th>
                                    <td class="highlight price">
                                        <?=Common::formatMoney($this->payment->getAmount())?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Hình thức:</th>
                                    <td><?=$this->translate($this->payment->getMethod())?></td>
                                </tr>
                                <tr>
                                    <th nowrap="">Ngày chứng từ:</th>
                                    <td><?=Common::formatDate($this->payment->getDate())?></td>
                                </tr>
                                <tr>
                                    <th>Trạng thái:</th>
                                    <?php
                                    $cls='badge-info';
                                    if($this->payment->getStatus()!=Define::STATUS_PAID)
                                        $cls='badge-danger';
                                    ?>
                                    <td><span class="right badge <?=$cls?>"><?=$this->translate($this->payment->getStatus())?></span></td>
                                </tr>
                                <tr>
                                    <th>Ghi chú:</th>
                                    <td><?=$this->payment->getNote()?></td>
                                </tr>
                                <tr>
                                    <th>Ngày tạo:</th>
                                    <td><?=Common::formatDateTime($this->payment->getCreatedDate())?></td>
                                </tr>
                                <tr>
                                    <th>Người tạo:</th>
                                    <td><?=$this->payment->getCreatedBy()?></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-default">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-paperclip"></i>
                            Chứng từ
                        </h3>
                    </div>
                    <div class="card-body">
                        <form action="#" class="dropzone" id="myDropzone"></form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /.content -->
<style>
    .small-box{border-radius:10px; margin-bottom:0px; padding-left:5px}
</style>
<link rel="stylesheet" href="/vendor/adminlte/plugins/dropzone/css/dropzone.min.css"/>
<link rel="stylesheet" href="/vendor/adminlte/plugins/dropzone/custom.css"/>
<script src="/vendor/adminlte/plugins/dropzone/js/dropzone.min.js"></script>
<script src="/vendor/adminlte/plugins/dropzone/custom.js"></script>
<link rel="stylesheet" href="/vendor/adminlte/plugins/lightbox2/css/lightbox.min.css"/>
<script src="/vendor/adminlte/plugins/lightbox2/js/lightbox.min.js"></script>

<script>
    const dz = initCustomDropzone({
        selector: "#myDropzone",
        uploadUrl: "<?=$this->url('supplier-payment',['action'=>'upload-file','id'=>$this->payment->getPublicId()])?>",
        deleteUrl: "<?=$this->url('supplier-payment',['action'=>'delete-file'])?>",
        fileListUrl: "<?=$this->url('supplier-payment',['action'=>'file-list','id'=>$this->payment->getId()])?>",
        defaultMessage:'Kéo thả chứng từ vào đây để upload chứng từ. (Chỉ upload file ảnh, PDF). Dung lượng ảnh không quá 10MB'
    });

    $( document ).ready(function() {
        $('.btn-payment-confirm').on('click', function(e){
            e.preventDefault();
            let text = 'Xác nhận thanh toán sẽ làm giảm công nợ với NCC! Nhấn <b>Đồng ý</b> nếu bạn vẫn muốn tiếp tục.';
            Swal.fire({
                title: "Xác nhận thanh toán <?=Common::formatMoneyVND($this->payment->getAmount())?>?",
                html: text,
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Đồng ý",
                cancelButtonText:"Đóng"
            }).then((result) => {
                if(result.isConfirmed) {
                    run_waitMe();
                    let url = '<?=$this->url('supplier-payment',["action"=>'confirm'])?>';
                    $.ajax({
                        method: "POST",
                        headers: {Accept: "application/json; charset=utf-8"},
                        url: url,
                        data: {id:<?=$this->payment->getId()?>},
                        cache: false,
                        dataType:'json'
                    }).done(function(response) {
                        if(response.status===1){
                            Toast.fire({title: response.message, icon: 'success'});
                            waitMeMessage('<?=Define::MESSAGE_WINDOW_REDIRECT?>')
                            location.reload();
                        }else{
                            Toast.fire({title: response.message, icon: 'error'});
                            stop_waitMe();
                        }
                    });
                }
            });
        });

        $('.btn-payment-cancel').on('click', function(e){
            e.preventDefault();
            let text = 'Huỷ phiếu thanh toán sẽ làm tăng công nợ với NCC! Nhấn <b>Đồng ý</b> nếu bạn vẫn muốn tiếp tục.';
            Swal.fire({
                title: "Huỷ phiếu thanh toán <?=Common::formatMoneyVND($this->payment->getAmount())?>?",
                html: text,
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Đồng ý",
                cancelButtonText:"Đóng"
            }).then((result) => {
                if(result.isConfirmed) {
                    run_waitMe();
                    let url = '<?=$this->url('supplier-payment',["action"=>'cancel'])?>';
                    $.ajax({
                        method: "POST",
                        headers: {Accept: "application/json; charset=utf-8"},
                        url: url,
                        data: {id:<?=$this->payment->getId()?>},
                        cache: false,
                        dataType:'json'
                    }).done(function(response) {
                        if(response.status==1){
                            Toast.fire({title: response.message, icon: 'success'});
                            waitMeMessage('<?=Define::MESSAGE_WINDOW_REDIRECT?>')
                            location.reload();
                        }else{
                            Toast.fire({title: response.message, icon: 'error'});
                            stop_waitMe();
                        }
                    });
                }
            });
        });

        $('#btn-delete-payment').on('click', function(e){
            e.preventDefault();

            let text = 'Bạn có chắc muốn xoá phiếu thanh toán? Nhấn <b>Đồng ý</b> nếu bạn vẫn muốn tiếp tục.';
            Swal.fire({
                title: "Xoá phiếu thanh toán <?=Common::formatMoneyVND($this->payment->getAmount())?>?",
                html: text,
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Đồng ý",
                cancelButtonText:"Đóng"
            }).then((result) => {
                if(result.isConfirmed) {
                    run_waitMe();
                    let url = '<?=$this->url('supplier-payment',["action"=>'delete'])?>';
                    $.ajax({
                        method: "POST",
                        headers: {Accept: "application/json; charset=utf-8"},
                        url: url,
                        data: {id:<?=$this->payment->getId()?>},
                        cache: false,
                        dataType:'json'
                    }).done(function(response) {
                        if(response.status===1){
                            Toast.fire({title: response.message, icon: 'success'});
                            waitMeMessage('<?=Define::MESSAGE_WINDOW_REDIRECT?>')
                            window.location.href="<?=$this->url('supplier-payment',['action'=>'list'])?>";
                        }else{
                            Toast.fire({title: response.message, icon: 'error'});
                            stop_waitMe();
                        }
                    });
                }
            });
        });
    })

</script>
