<?php
use Sulde\Service\Common\Common;
use Sulde\Service\Common\Define;
?>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <div class="card card-default">
                    <div class="card-header">
                        <div class="user-block">
                            <img class="img-circle" src="/assets/images/avatar.png">
                            <span class="username"><a href="#"><?=$this->purchaseReturn->getPurchase()->getSupplier()->getName()?></a></span>
                            <span class="description"><?=$this->purchaseReturn->getPurchase()->getSupplier()->getAddress()?> - <?=Common::formatDateTime($this->purchaseReturn->getCreatedDate())?></span>
                        </div>
                        <?php
                        //chi hiển thị button approval khi chua duyet
                        if($this->purchaseReturn->getStatus()!=Define::STATUS_APPROVED){
                            ?>
                            <div class="card-tools">
                                <button id="btnApproval" class="btn btn-danger">
                                    <span class="fa fa-gavel"></span>
                                    Phê duyệt
                                </button>
                            </div>
                        <?php }?>

                    </div>
                    <div class="card-body">
                        <table class="display" id="tblProductReturn">
                            <thead>
                            <tr>
                                <th></th>
                                <th>STT</th>
                                <th></th>
                                <th>Mã</th>
                                <th>Sản phẩm</th>
                                <th class="number">Quy cách</th>
                                <th>Đơn vị</th>
                                <th class="number" nowrap="">SL trả</th>
                                <th class="number" nowrap="">Đơn giá</th>
                                <th class="number" nowrap="">Thành tiền</th>
                                <th class="number" nowrap="">Thuế GTGT</th>
                                <th class="number" nowrap="">Tiền thuế GTGT</th>
                                <th class="number" nowrap="">Chiết khẩu</th>
                                <th class="number" nowrap="">Tiền chiết khẩu</th>
                                <th class="number" nowrap="">Tiền hoàn trả</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                            <tfoot></tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="callout callout-info">
                    <h5><i class="fas fa-info"></i> Ghi chú:</h5>
                    <?=$this->purchaseReturn->getNote()?>
                </div>

                <div class="card card-default collapsed-card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-info-circle"></i>
                            Thông tin phiếu trả
                        </h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <tr>
                                    <th>Nhà cung cấp: </th>
                                    <td class="text-danger highlight"><?=$this->purchaseReturn->getPurchase()->getSupplier()->getName()?></td>
                                </tr>
                                <tr>
                                    <th>Ngày tạo: </th>
                                    <td><?=Common::formatDateTime($this->purchaseReturn->getCreatedDate())?></td>
                                </tr>
                                <tr>
                                    <th>Người tạo: </th>
                                    <td><?=$this->purchaseReturn->getCreatedBy()?></td>
                                </tr>
                                <tr>
                                    <th>Ngày duyệt: </th>
                                    <td><?=Common::formatDateTime($this->purchaseReturn->getApprovedDate())?></td>
                                </tr>
                                <tr>
                                    <th>Người duyệt: </th>
                                    <td><?=$this->purchaseReturn->getApprovedBy()?></td>
                                </tr>
                        </table>
                        </div>
                    </div>
                </div>

                <div class="card card-default">
                    <div class="card-body">
                        <table style="width: 100%">
                            <tr>
                                <td class="pb-2">Mã phiếu trả hàng: </td>
                                <th class="border-bottom pb-2 text-right"><?=$this->purchaseReturn->getCode()?></th>
                            </tr>
                            <tr>
                                <td class="pb-2">Trạng thái:</td>
                                <td class="border-bottom pb-2 pt-2 text-right">
                                    <?php
                                    $cls=($this->purchaseReturn->getStatus()==Define::STATUS_APPROVED)?'badge-success':'badge-danger';
                                    ?>
                                    <span class="badge <?=$cls?>">
                                            <?=$this->translate($this->purchaseReturn->getStatus())?>
                                        </span>
                                </td>
                            </tr>
                            <tr>
                                <td class="pt-2"></td>
                                <td class="border-bottom text-right pt-2 pb-2">
                                    <a href="<?=$this->url('purchase-admin',['action'=>'detail','id'=>$this->purchaseReturn->getPurchase()->getPublicId()])?>">
                                        Chứng từ gốc
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <th class="pt-2">Tiền hàng hoàn trả:</th>
                                <th class="price border-bottom text-right pt-2 pb-2 total-product-return"></th>
                            </tr>
                            <tr>
                                <td class="pt-2">Thuế xuất:</td>
                                <td class="price text-right border-bottom pt-2 pb-2 total-product-vat-return"></td>
                            </tr>
                            <tr>
                                <td class="pt-2">Chiết khẩu:</td>
                                <td class="price text-right border-bottom pt-2 total-product-discount-return"></td>
                            </tr>
                        </table>
                    </div>
                    <div class="card-footer border-top">
                        <div class="row">
                            <label class="col-md-6 col-6">
                                Tổng tiền hoàn trả:
                            </label>
                            <div class="col-md-6 col-6 price text-right text-lg grand-total">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
<!--Datatable fixed column-->
<script src="/vendor/adminlte/plugins/datatables/2.3.5/js/dataTables.fixedColumns.min.js"></script>
<link rel="stylesheet" href="/vendor/adminlte/plugins/datatables/2.3.5/css/fixedColumns.dataTables.css">
<script>
    let tblProductReturn;
    $( document ).ready(function() {
        tblProductReturn=$('#tblProductReturn').DataTable({
            responsive: isMobile,
            fixedColumns: isMobile ? false : {
                start: 4
            },
            select:true,
            paging: true,
            pageLength:<?=\Sulde\Service\Common\Define::ITEM_PAGE_COUNT?>,
            ordering: false,
            stateSave: false,
            autoWidth: false,
            serverSide:false,
            scrollCollapse: true,
            scrollX: true,
            scrollY: '60vh',
            layout: {
                topStart: null,  // ❌ tắt ô search mặc định
                topEnd: null,    // ❌ tắt length dropdown mặc định
                top: ['search', 'pageLength']
            },
            language: {
                searchPlaceholder: "Tìm kiếm theo tên sản phẩm."
            },
            columnDefs: [
                {
                    targets: [1,3,5,6,10,11,12,13], className: 'min-desktop'
                }, {
                    name:'rowData', targets: 0, visible: false
                }, {
                    name: 'img',
                    targets: 2,
                    width: '50px',
                    createdCell: function (td, cellData, rowData, row, col) {
                        $(td).html(`<img src="${cellData}">`);
                    }
                },{
                    name: 'barcode',
                    targets: 3,
                    width: '50px',
                    createdCell: function (td, cellData, rowData, row, col) {
                        $(td).html(subBarcode(cellData));
                    }
                },{
                    name: 'name',
                    targets: 4,
                    width: '250px',
                    createdCell: function (td, cellData, rowData, row, col) {
                        let product=rowData[0].product;
                        let content=`<a href="<?=$this->url('product-admin',['action'=>'detail'])?>/${product.public_id}" class="title name">${product.name}</a><br>`
                        content+=(product.status==='<?=Define::DEFAULT_UN_ACTIVE?>' || product.status===null)?'<span class="badge badge-danger"><?=Define::PRODUCT_TEXT_UN_ACTIVE?></span> ':'';

                        content+=(product?.purchase_detail_latest?.price)
                            ?`<span class="badge badge-info" data-toggle="tooltip" data-placement="bottom" title="NCC: ${product.purchase_detail_latest.supplier.name}">
                         Giá nhập gần đây: ${formatMoney(product.purchase_detail_latest.price)} ${product.purchase_detail_latest.unit_name}
                         </span><br>`
                            :'<span class="badge badge-info">Nhập lần đầu</span> ';

                        content +=`<span class="badge badge-warning">Tồn kho: ${product.inventory} ${product.unit.name}</span>`;

                        $(td).html(content);
                    }
                },{
                    name:'qc',
                    targets: 5,
                    width: '150px'
                },{
                    name:'unit',
                    targets: 6,
                    width: '100px'
                },{
                    name:'qty',
                    targets: 7,
                    width: '70px',
                    className: 'highlight-col'
                },{
                    name: 'price',
                    targets: 8,
                    width: '100px',
                    className: 'highlight-col',
                    createdCell: function (td, cellData, rowData, row, col) {
                        $(td).html(cellData);
                    }
                },{
                    name: 'total_price',
                    targets: 9,
                    width: '100px',
                    className: 'price highlight-col'
                },{
                    name:'discount',
                    targets: 12,
                    className: 'text-right'
                },{
                    name:'product_total_return',
                    targets: 14,
                    className: 'price'
                },{
                    name: 'button',
                    targets: 15,
                    width: '50px',
                    createdCell: function (td, cellData, rowData, row, col) {
                        let button='<button type="button" class="trash btn btn-danger btn-rounded btn-sm"><i class="fas fa-trash-alt"></i></button>';
                        let purchaseReturnStatus='<?=$this->purchaseReturn->getStatus()?>';
                        if(purchaseReturnStatus=='<?=Define::STATUS_APPROVED?>')
                            button='';
                        $(td).html(button);
                    }
                }
            ],
            ajax: {
                url: '<?=$this->url('purchase-return-admin',['action'=>'detail'])?>',
                type: 'POST',
                data:{id:'<?=$this->purchaseReturn->getId()?>'},
                dataSrc: function (response) {
                    let data=[];
                    let i=1;
                    $.each( response, function( key, value ) {
                        let dataItem=[];
                        dataItem.push(value);
                        dataItem.push(i++);
                        dataItem.push(value.product.default_image);
                        dataItem.push(value.variant.barcode);
                        dataItem.push(value.product.name);
                        dataItem.push(value.variant.name);
                        dataItem.push(value.variant.unit.name);
                        dataItem.push(formatNumber(value.qty));
                        dataItem.push(formatMoney(formatNumber(value.price)));
                        dataItem.push(formatMoney(formatNumber(value.amount)));
                        dataItem.push(intVal(value.vat))
                        dataItem.push(formatMoney(value.vat_amount))

                        let discount = (value.discount_type==='<?=Define::PERCENT?>')?intVal(value.discount)+'%':formatMoneyVND(value.discount);
                        dataItem.push(discount);

                        dataItem.push(formatMoney(value.discount_amount))

                        let totalVatAmount=value.vat_amount*value.qty;
                        let totalProductDiscount=value.discount_amount*value.qty;
                        let totalProductReturnAmount=value.amount + totalVatAmount - totalProductDiscount;
                        dataItem.push(formatMoney(totalProductReturnAmount));
                        dataItem.push(value.return_detail_id);
                        data.push(dataItem);
                    });
                    return data;
                }
            }
        });
        tblProductReturn.on('draw.dt', function () {
            let datas = tblProductReturn.rows().data().toArray();
            calcAmountInfo(datas);
        });

        $("#tblProductReturn")
            .on("click", ".trash", function() {
                let btn=$(this);
                let row = $(this).closest('tr');
                let data = tblProductReturn.row( row ).data()[0];
                let text = `Bạn có chắc muốn xoá sản phẩm <b>${data.product.name}</b> khỏi phiếu trả hàng?`;

                Swal.fire({
                    title: "Xoá dữ liệu?",
                    html: text,
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Xoá sản phẩm",
                    cancelButtonText:"Huỷ xoá"
                }).then((result) => {
                    if(result.isConfirmed) {
                        // run_waitMe();
                        // 🔒 LOCK ROW
                        row.addClass('row-deleting');
                        btn.prop('disabled', true);
                        // loading
                        btn.find('i')
                            .removeClass('fa-trash-alt')
                            .addClass('fa-spinner fa-spin');

                        var url = "<?=$this->url('purchase-return-admin',['action'=>'delete-product'])?>";
                        $.ajax({
                            method: "POST",
                            url: url,
                            data: {return_detail_id:data.return_detail_id},
                            headers: {Accept: "application/json; charset=utf-8"}
                        }).done(function (response) {
                            if(response.status){
                                Toast.fire({title: response.message, icon: 'success'});
                                row.fadeOut(300, function () {
                                    tblProductReturn.row(row).remove().draw(false);
                                });
                            }
                            else{
                                Swal.fire({
                                    icon: "error",
                                    title: "Oops...",
                                    text: response.message
                                });
                                row.removeClass('row-deleting');
                                btn.find('i').removeClass('fa-spinner fa-spin').addClass('fa-trash-alt')
                                btn.prop('disabled', false);
                            }
                        })
                    }
                });
            });

        $('#btnApproval').on('click', function(e){
            e.preventDefault();
            let text = 'Phê duyệt sẽ làm thay đổi tồn kho của sản phẩm và công nợ với NCC! Nhấn <b>Phê duyệt</b> nếu bạn vẫn muốn tiếp tục.';

            Swal.fire({
                title: "Phê duyệt phiếu trả hàng?",
                html: text,
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Phê duyệt",
                cancelButtonText:"Huỷ trả"
            }).then((result) => {
                if(result.isConfirmed) {
                    run_waitMe();
                    var url = "<?=$this->url('purchase-return-admin',['action'=>'approval'])?>";
                    $.ajax({
                        method: "POST",
                        headers: {Accept: "application/json; charset=utf-8"},
                        url: url,
                        data: {id:'<?=$this->purchaseReturn->getId()?>'}
                    }).done(function (response) {
                        if(response.status){
                            Toast.fire({title: response.message, icon: 'success'});
                            location.reload();
                        }
                        else{
                            Swal.fire({
                                icon: "error",
                                title: "Oops...",
                                text: response.message
                            });
                            // Toast.fire({title: response.message, icon: 'error'});
                        }
                        stop_waitMe();
                    })
                }
            });

        });
    });
    function calcAmountInfo(datas){
        let totalProductReturn=0,totalVat=0,totalDiscount=0;
        $.each(datas, function(index, value) {
            let returnDetail=value[0];
            totalProductReturn +=formatNumber(returnDetail.amount);
            totalVat +=formatNumber(returnDetail.vat_amount);
            totalDiscount +=formatNumber(returnDetail.discount_amount);
        });
        let grandTotal=totalProductReturn+totalVat-totalDiscount;

        $('.total-product-return').html(formatMoney(totalProductReturn));
        $('.total-product-vat-return').html(formatMoney(totalVat));
        $('.total-product-discount-return').html(formatMoney(totalDiscount));
        $('.grand-total').html(formatMoney(grandTotal));
    }
</script>