<?php

use Sulde\Service\Common\Common;
use Sulde\Service\Common\ConfigManager;
use Sulde\Service\Common\Define;
?>
<section class="content">
    <div class="container-fluid">
        <div class="card card-default">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <table class="display" id="tblProduct">
                            <thead>
                            <tr>
                                <th></th>
                                <th class="number">No.</th>
                                <th>Nhà cung cấp</th>
                                <th>Tổng đơn</th>
                                <th>Trạng thái</th>
                                <th>Ghi chú</th>
                                <th>Người tạo</th>
                                <th>Ngày tạo</th>
                                <th>Người duyệt</th>
                                <th>Ngày duyệt</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th></th>
                                <th class="number">No.</th>
                                <th>Nhà cung cấp</th>
                                <th>Tổng đơn</th>
                                <th>Trạng thái</th>
                                <th>Ghi chú</th>
                                <th>Người tạo</th>
                                <th>Ngày tạo</th>
                                <th>Người duyệt</th>
                                <th>Ngày duyệt</th>
                                <th></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    let tblProduct;
    $(document).ready(function () {
        tblProduct=$('#tblProduct').DataTable({
            responsive:true,
            paging: true,
            pageLength:<?=\Sulde\Service\Common\Define::ITEM_PAGE_COUNT?>,
            ordering: false,
            // info: false,
            processing: true,
            serverSide: true,
            stateSave: false,
            layout: {
                topStart: null,  // ❌ tắt ô search mặc định
                topEnd: null,    // ❌ tắt length dropdown mặc định
                top: ['search', 'pageLength']
            },
            language: {
                searchPlaceholder: "Tìm kiếm theo tên NCC."
            },
            rowCallback: function(row, data) {
                if(data[0].status!='<?=Define::STATUS_APPROVED?>')
                    row.classList.add('overdue');
            },
            columnDefs: [
                { targets: [1,5,6,7,8,9], className: 'min-desktop'},
                { name:'rowData', targets: 0, visible: false},
                { name: 'name', targets: 2,
                    createdCell:function (td, cellData, rowData, row, col){
                        let name = '<a class="title" href="<?=$this->url('purchase-return-admin',['action'=>'detail'])?>/'+rowData[0].public_id+'">'+cellData+'</a>'
                        $(td).html(name);
                    }
                },
                {
                    name: 'total',
                    targets: 3,
                    className: 'number price',
                    createdCell: function (td, cellData, rowData, row, col) {
                        $(td).html(formatMoney(cellData));
                    }
                }, {
                    name: 'status',
                    targets: 4,
                    createdCell: function (td, cellData, rowData, row, col) {
                        let statusLable=`<span class="badge bg-warning">${rowData[0].status_label}</span>`;
                        if(rowData[0].status=='<?=Define::STATUS_APPROVED?>')
                            statusLable=`<span class="badge bg-success">${rowData[0].status_label}</span>`;
                        $(td).html(statusLable);
                    }
                }, {
                    name: 'button',
                    targets: 10,
                    className: 'dt-body-nowrap',
                    createdCell: function (td, cellData, rowData, row, col) {
                        let button='<button type="button" class="trash btn btn-danger btn-rounded btn-sm"><i class="fas fa-trash-alt"></i></button>';
                        if(rowData[0].status=='<?=\Sulde\Service\Common\Define::STATUS_APPROVED?>')
                            button='';

                        $(td).html(button);
                    }
                }
            ],
            ajax: {
                url: '<?=$this->url('purchase-return-admin',['action'=>'list'])?>',
                type: 'POST',
                dataSrc: function (json) {
                    let data=[];
                    let i=1;
                    $.each( json.data, function( key, value ) {
                        let dataItem=[];
                        let status=`<span class="label ${value.status=='<?=Define::STATUS_APPROVED?>' ? 'label-success' : 'label-danger'} label-form">${value.status}</span>`;

                        dataItem.push(value);
                        dataItem.push(i);
                        dataItem.push(value.supplier.name);
                        dataItem.push(value.total_amount_return);
                        dataItem.push(status);
                        dataItem.push(value.note);
                        dataItem.push(value.created_by);
                        dataItem.push(value.created_date);
                        dataItem.push(value.approved_by);
                        dataItem.push(value.approved_date);
                        dataItem.push('status');

                        data.push(dataItem);
                        i++;
                    });
                    return data;
                }
            }
        }).on('click', 'tbody tr', (e) => {
            let classList = e.currentTarget.classList;

            if (classList.contains('tr-selected')) {
                classList.remove('tr-selected');
            }
            else {
                tblProduct.rows('.tr-selected').nodes().each((row) => row.classList.remove('tr-selected'));
                classList.add('tr-selected');
            }
        });
        $("#tblProduct")
            .on("click", ".trash", function() {
                let row = $(this).closest('tr');
                let data = tblProduct.row( row ).data()[0];

                let text = `Bạn có chắc muốn xoá phiếu trả hàng: ${data.supplier.name}?`;

                Swal.fire({
                    title: "Xoá dữ liệu?",
                    text: text,
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Xoá phiếu",
                    cancelButtonText:"Huỷ xoá"
                }).then((result) => {
                    if(result.isConfirmed) {
                        run_waitMe();
                        let url = "<?=$this->url('purchase-return-admin',['action'=>'delete'])?>";
                        $.ajax({
                            method: "POST",
                            url: url,
                            data: {purchase_return_id:data.purchase_return_id},
                            headers: {Accept: "application/json; charset=utf-8"}
                        }).done(function (response) {
                            if(response.status){
                                Toast.fire({title: response.message, icon: 'success'});
                                row.fadeOut(400);
                            }
                            else{
                                Swal.fire({icon: "error", title: "Oops...", text: response.message});
                            }
                            stop_waitMe();
                        })
                    }
                });
            });
    });
</script>