<?php
use Sulde\Service\Common\Common;
?>
<section class="content">
    <div class="container-fluid">
        <div class="card card-default">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <?=$this->partial('admin/partial/sub-dashboard-item.phtml', array('privileges' => $this->privileges,'privilegeId'=>$this->privilegeId));?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {

    });
</script>