<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <div class="card-tools">
                            <a href="<?=$this->url('supplier-admin',['action'=>'add'])?>" class="btn btn-info btn-flat">
                                <span class="fa fa-plus"></span>
                                Thêm mới nhà cung cấp
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="tblSupplier" class="display">
                            <thead>
                            <tr>
                                <th></th>
                                <th class="number">No.</th>
                                <th>Tên nhà cung cấp</th>
                                <th>Tên viết tắt</th>
                                <th>Địa chỉ</th>
                                <th>Điện thoại</th>
                                <th>Mã số thuế</th>
                                <th>Người liên hệ</th>
                                <th>Email</th>
                                <th>Ngày tạo</th>
                                <th>Người tạo</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th></th>
                                <th class="number">No.</th>
                                <th>Tên nhà cung cấp</th>
                                <th>Địa chỉ</th>
                                <th>Điện thoại</th>
                                <th>Mã số thuế</th>
                                <th>Người liên hệ</th>
                                <th>Email</th>
                                <th>Ngày tạo</th>
                                <th>Người tạo</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="/vendor/adminlte/plugins/datatables/2.3.5/js/dataTables.select.min.js"></script>
<script>
    $( document ).ready(function() {
        let tblSupplier=$('#tblSupplier').DataTable({

            select:true,
            paging: true,
            pageLength:<?=\Sulde\Service\Common\Define::ITEM_PAGE_COUNT?>,
            ordering: false,
            processing: true,
            serverSide: true,
            layout: {
                topStart: null,  // ❌ tắt ô search mặc định
                topEnd: null,    // ❌ tắt length dropdown mặc định
                top: ['search', 'pageLength']
            },
            language: {
                searchPlaceholder: "Tìm kiếm theo tên nhà cung cấp."
            },
            initComplete: function() {
                $(this.api().table().container()).find('input[type="search"]').attr('autocomplete', 'off');
            },
            columnDefs: [
                {
                    name:'rowData',
                    targets: 0,
                    visible: false
                },{
                    name:'name',
                    targets: 2,
                    className:'title',
                    createdCell: function (td, cellData, rowData, row, col) {
                        let data=rowData[0];
                        let name = '<a href="<?=$this->url('supplier-debt',['action'=>'detail'])?>/'+data.public_id+'">'+data.name+'</a>'
                        $(td).html(name);
                    }
                }
            ],
            ajax: {
                url: '<?=$this->url('supplier-admin',['action'=>'list'])?>',
                type: 'POST',
                dataSrc: function (json) {
                    let data=[];
                    let i=1;
                    $.each( json.data, function( key, value ) {
                        let dataItem=[];
                        dataItem.push(value);
                        dataItem.push(i);
                        dataItem.push(value.name);
                        dataItem.push(value.short_name);
                        dataItem.push(value.address);
                        dataItem.push(value.mobile);
                        dataItem.push(value.tax_code);
                        dataItem.push(value.contact_person);
                        dataItem.push(value.email);
                        dataItem.push(value.created_date);
                        dataItem.push(value.created_by);

                        data.push(dataItem);
                        i++;
                    });
                    return data;
                }
            }
        })
    })
</script>
