<?php

use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

?>
<div class="user-reset-password">
    <div class="container">
        <div class="row">

            <div class="col-md-5 col-xs-12">
                <div class="card" style="margin-bottom: 40px">
                    <div class="card-body">
                        <?php
                        echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR);
                        echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS);
                        $formHidden="";
                        if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)) $formHidden = 'style="display:none"';
                        ?>
                        <form id="frmResetPassword" action="<?=$this->url("user-reset-password")?>" class="form-reset" method="post" <?=$formHidden?>>
                            <p><?=$this->translate('Please enter the email address associated with your bestay account to receive a password reset link.')?></p>
                            <input type="text" id="resetEmail" name="resetEmail" class="form-control margin-bottom-15" placeholder="<?=$this->translate('Please enter a valid email address.')?>" autofocus="">
                            <button class="btn btn-primary btn-block" id="btnResetPassword" type="submit"><?=$this->translate('Reset password')?></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="/css/application/user.css"/>
<script src="/vendor/jquery/jquery.validate.min.js"></script>
<script>
    $(document).ready(function(){
        $('body').addClass('user-reset-password-bag');

        jQuery.validator.addMethod("isEmail", function(value, element) {
            var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            if(!regex.test(value)) {
                return false;
            }else{
                return true;
            }
        }, 'Please enter a valid email address.');

        $('#frmResetPassword').validate({
            rules : {
                resetEmail: {
                    required: true,
                    email: true,
                    isEmail:true
                }
            },
            messages : {
                resetEmail:{
                    required: "<?=$this->translate('Please enter a valid email address.')?>",
                    isEmail: "<?=$this->translate('Please enter the correct email.')?>",
                    email: "<?=$this->translate('Please enter the correct email.')?>"
                }
            },
            submitHandler : function (form) {
                var r= $('<span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>');
                $( "#btnResetPassword" ).append(r);
                $( "#btnResetPassword" ).attr("disabled", "disabled");
                form.submit();
            }

        });
    });
</script>