<?php

use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

?>
<div class="user-set-password">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <h1 class="title"><?=$this->translate('GO AND DISCOVER IN YOUR WAY')?></h1>
            </div>
            <div class="col-md-5 col-xs-12">
                <div class="card" style="margin-bottom: 40px">
                    <div class="card-body">
                        <?php
                        echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR);
                        echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS);
                        $formHidden="";
                        if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)) $formHidden = 'style="display:none"';
                        ?>
                        <form id="frmSetPassword" action="<?=$this->url("user-set-password")?>" class="form-reset" method="post" <?=$formHidden?>>
                            <p><?=$this->translate('Please enter a new password.')?></p>
                            <input type="hidden" name="token" value="<?=$this->token?>">
                            <input type="password" id="password" name="password" class="form-control margin-bottom-15" placeholder="<?=$this->translate('New password')?>" autofocus="">
                            <input type="password" id="confirm_password" name="confirm_password" class="form-control margin-bottom-15" placeholder="<?=$this->translate('Confirm password')?>" autofocus="">
                            <button class="btn btn-primary btn-block" id="btnChangePassword" type="submit"><?=$this->translate('Change password')?></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="/css/application/user.css"/>
<script src="/vendor/jquery/jquery.validate.min.js"></script>
<script>
    $(document).ready(function() {
        $('body').addClass('user-set-password-bag');

        $('#frmSetPassword').validate({
            rules : {
                password:{
                    required:true,
                    minlength:8,
                    maxlength:50
                } ,
                confirm_password: {
                    equalTo: "#password"
                }
            },
            messages : {
                password: {
                    required: "<?=$this->translate('Please enter a new password.')?>",
                    minlength: "<?=$this->translate('Password must be at least 8 characters.')?>",
                    maxlength: "<?=$this->translate('Password must not exceed 50 characters.')?>"
                },
                confirm_password: "<?=$this->translate('Enter confirm password same as password')?>"
            },
            submitHandler : function (form) {
                var r= $('<span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>');
                $( "#btnChangePassword" ).append(r);
                $( "#btnChangePassword" ).attr("disabled", "disabled");
                form.submit();
            }

        });
    });
</script>