<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">
                        <div class="card-tools">

                            <div class="btn-group">
                                <a href="<?=$this->url('purchase-admin',['action'=>'add'])?>" class="btn btn-info">
                                    <span class="fa fa-plus"></span>
                                    Tạo đơn nhập
                                </a>
                                <button type="button" class="btn btn-info dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <div class="dropdown-menu" role="menu" style="">
                                    <a class="dropdown-item" href="#">Từ hoá đơn đầu vào</a>
                                    <a class="dropdown-item" href="#">Từ excel file</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="display" id="tblProduct">
                            <thead>
                            <tr>
                                <th></th>
                                <th class="number">No.</th>
                                <th>Nhà cung cấp</th>
                                <th>Trạng thái</th>
                                <th>Tổng đơn</th>
                                <th>Chiết khấu</th>
                                <th>Sau chiết khấu</th>
                                <th>Thuế GTGT</th>
                                <th>Phụ phí</th>
                                <th>Phải thanh toán</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                            <tfoot></tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    let tblProduct;
    $(document).ready(function () {
        tblProduct=$('#tblProduct').DataTable({
            select:true,
            responsive:true,
            paging: true,
            pageLength:<?=\Sulde\Service\Common\Define::ITEM_PAGE_COUNT?>,
            ordering: false,
            processing: true,
            serverSide: true,
            stateSave: true,
            layout: {
                topStart: null,  // ❌ tắt ô search mặc định
                topEnd: null,    // ❌ tắt length dropdown mặc định
                top: ['search', 'pageLength']
            },
            language: {
                searchPlaceholder: "Tìm kiếm theo tên NCC."
            },
            initComplete: function() {
                $(this.api().table().container()).find('input[type="search"]').attr('autocomplete', 'off');
            },
            columnDefs: [
                { targets: [4,5,6,7,8,10], className: 'min-desktop'},
                { name:'rowData', targets: 0, visible: false},
                { name: 'name', targets: 2,
                    createdCell:function (td, cellData, rowData, row, col){
                        let name = '<a href="<?=$this->url('purchase-admin',['action'=>'detail'])?>/'+rowData[0].public_id+'">'+cellData+'</a>'
                        if(rowData[0].note)
                            name+='<p><b>Note:</b> <i>'+rowData[0].note+'</i></p>';
                        $(td).html(name);
                    }
                },{
                    name: 'total',
                    targets: 4,
                    className: 'number price'
                },{
                    name: 'payable',
                    targets: 9,
                    className: 'price'
                },{
                    name: 'button',
                    targets: 10,
                    className: 'dt-body-nowrap',
                    createdCell: function (td, cellData, rowData, row, col) {
                        let button='<button type="button" class="btn btn-danger btn-rounded btn-sm trash"><i class="fas fa-trash-alt"></i></button>';
                        if(rowData[0].status=='<?=\Sulde\Service\Common\Define::PURCHASE_APPROVAL?>')
                            button='';
                        $(td).html(button);
                    }
                }
            ],
            ajax: {
                url: '<?=$this->url('purchase-admin',['action'=>'list'])?>',
                type: 'POST',
                dataSrc: function (json) {
                    let data=[];
                    let i=1;
                    $.each( json.data, function( key, value ) {
                        let dataItem=[];
                        let status=`<span class="badge ${value.status!='<?=\Sulde\Service\Common\Define::STATUS_APPROVED?>' ? 'badge-warning' : 'badge-success'}">${value.status_name}</span>`;
                        dataItem.push(value);
                        dataItem.push(i);
                        dataItem.push(value.supplier.name);
                        dataItem.push(status);
                        dataItem.push(formatMoney(value.total_order_amount));
                        let totalDiscount=intVal(value.discount_amount.order_discount_amount)+intVal(value.discount_amount.product_discount_amount);
                        dataItem.push(formatMoney(totalDiscount));
                        let totalAmountAfterDiscount=value.total_order_amount-totalDiscount
                        dataItem.push(formatMoney(totalAmountAfterDiscount));
                        dataItem.push(formatMoney(value.total_vat_amount));
                        dataItem.push(formatMoney(value.total_additional_fees_amount));
                        let totalAmountPayable=value.total_order_amount+value.total_vat_amount+value.total_additional_fees_amount-totalDiscount;
                        dataItem.push(formatMoney(totalAmountPayable));

                        dataItem.push('');

                        data.push(dataItem);
                        i++;
                    });
                    return data;
                }
            }
        })

        $("#tblProduct")
            .on("click", ".trash", function() {
                let btn=$(this);
                let row = $(this).closest('tr');
                let data = tblProduct.row( row ).data()[0];

                let text = "Bạn có chắc muốn xoá đơn hàng?";
                Swal.fire({
                    title: "Xoá dữ liệu?",
                    text: text,
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Xoá đơn",
                    cancelButtonText:"Huỷ xoá"
                }).then((result) => {
                    if(result.isConfirmed) {
                        row.addClass('row-deleting');
                        btn.prop('disabled', true);
                        btn.find('i')
                            .removeClass('fa-trash-alt')
                            .addClass('fa-spinner fa-spin');

                        var url = "<?=$this->url('purchase-admin',['action'=>'delete'])?>";
                        $.ajax({
                            method: "POST",
                            headers: {Accept: "application/json; charset=utf-8"},
                            url: url,
                            data: {id:data.id}
                        }).done(function (response) {
                            if(response.status){
                                Toast.fire({title: response.message, icon: 'success'});
                                row.fadeOut(300, function () {
                                    tblProduct.row(row).remove().draw(false);
                                });
                                // tblProduct.clear().draw();
                            }else{
                                Swal.fire({icon: "error", title: "Oops...", text: response.message});
                                row.removeClass('row-deleting');
                                btn.find('i').removeClass('fa-spinner fa-spin').addClass('fa-trash-alt')
                                btn.prop('disabled', false);
                            }
                        })
                    }
                });

            });
    });
</script>