<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Đặt phòng homestay giá rẻ nhanh chóng, tìm kiếm homestay, nhà nghỉ, khách sạn trên bản đồ và tìm chỉ đường tại bestay')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <meta data-n-head="true" name="robots" content="index,follow">
        <meta data-n-head="true" name="author" content="BESTAY">
        <meta data-n-head="true" name="description" content="Kênh chính thức về Homestay tại Việt Nam, Kinh nghiệm đặt phòng homestay, Ưu Đãi Tốt Nhất Giảm Tới 40% Ngay Hôm Nay. Bạn là chủ Homestay đăng tin ngày để hàng nghìn người tìm thấy homestay của bạn, đăng tin một lần có khách mãi mãi. Homestay Sapa, Homestay Đà Lạt, Homestay Hà Nội, Homestay Hồ Chí Minh, Homestay Vũng Tàu, Homestay Tam Đảo, Homestay Hội An, Homestay Đà Nẵng, Homestay Hạ Long, Homestay Phan Thiết.">
        <meta data-n-head="true" name="apple-mobile-web-app-title" content="vnhomestay.com.vn">
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon-32x32.png'])?>
        <!-- CSS INCLUDE -->
        <link rel="stylesheet" type="text/css" id="theme" href="/vendor/bootstrap/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" id="theme" href="/vendor/fontawesome-free/css/all.css"/>
<!--        /joli/css/bootstrap/bootstrap.min.css-->
        <link rel="stylesheet" type="text/css" id="theme" href="/css/simple-sidebar.css"/>
        <link rel="stylesheet" href="/css/jquery.mCustomScrollbar.min.css">

        <link href="/vendor/MDB_4.8.7/css/mdb.min.css" rel="stylesheet">
		<script data-ad-client="ca-pub-9910654742181507" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="/vendor/jquery/jquery.min.js"></script>
        <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- jQuery Custom Scroller CDN -->
        <script src="/js/jquery.mCustomScrollbar.concat.min.js"></script>      	
<!--        <script src="/vendor/MDB_4.8.7/js/mdb.min.js"></script>-->

    </head>
    <body>
    <div class="overlay"></div>
    <div class="d-flex" id="wrapper">
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <?= $this->content ?>
            </div>
        </div>
    </div>
    </body>
</html>
