<?php
if(count($reviews)) {
    $rate=[];
    $totalStar;
    $totalReview=count($reviews);
    foreach($reviews as $review):
        $star = $review->getStar();
        if($star!==null and $star>0){
            $rate[$star] = $rate[$star]+1;
            $totalStar+=$star;
        }
    endforeach;

    $rateCount = $totalStar/$totalReview;
?>
    <div class="row rate-bag">
        <div class="col-md-12">
            <div class="padding-top-15 padding-bottom-15">
                <b><?=$this->translate('Rate')?></b>
            </div>
        </div>
        <div class="col-5 col-md-5 text-center padding-bottom-15">
            <h1 class="rating-num"><?=round($rateCount,1)?></h1>
            <div class="rating">
                <?php
                for ($x = 1; $x <= round($rateCount); $x++) {
                    echo '<span class="fa fa-star star-yellow"></span>';
                }
                for ($x = round($rateCount)+1; $x <= 5; $x++) {
                    echo '<span class="fa fa-star"></span>';
                }
                ?>
            </div>
            <div>
                <span class="fa fa-user"></span> <?=$totalReview?> total
            </div>
            <!--<a href="#comment"><?=$this->translate('Write a comment')?></a>-->
        </div>
        <div class="col-7 col-md-7">
            <div class="row rating-desc">
                <?php
                ksort($rate);
                foreach($rate as $key=>$value):
                    ?>
                    <div class="col-3 col-md-3 text-right padding-left-0">
                        <span class="fa fa-star"></span><?=$key?>
                    </div>
                    <div class="col-9 col-md-9 rating-item padding-left-0">
                        <div class="progress">
                            <div class="progress-bar bg-star-<?=$key?>" role="progressbar" aria-valuenow="20"
                                 aria-valuemin="0" aria-valuemax="100" style="width: <?=round($value/$totalReview*100,1)?>%"><?=round($value/$totalReview*100,1)?>%
                            </div>
                        </div>
                    </div>
                <?php
                endforeach
                ?>
            </div>
        </div>
    </div>
<?php }?>
<style>
    .rate-bag{background-color: aliceblue;}
    .comment-wrapper .media-list .media img {
        width:64px;
        height:64px;
        border:2px solid #e5e7e8;
    }

    .comment-wrapper .media-list .media {
        border-bottom:1px dashed #efefef;
        margin-bottom:25px;
    }
    .comment-wrapper ul{padding-left: 0px;}
    .comment-wrapper .media-body{padding-left: 10px;}
    .comment{
        padding-top: 15px;
    }
    /*Rating*/
    .starrating > input {display: none;}  /* Remove radio buttons */

    .starrating > label:before {
        margin: 2px;
        font-size: 1em;
        display: inline-block;
    }

    .starrating > label
    {
        color: #222222; /* Start color when not clicked */
    }

    .starrating > input:checked ~ label
    { color: #ffca08 ; } /* Set yellow color when star checked */

    .starrating > input:hover ~ label
    { color: #ffca08 ;  } /* Set yellow color when star hover */
    .risingstar{width: 120px; margin-top:5px}

</style>

<div class="bootstrap comment">
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="comment-wrapper">
                <ul class="media-list">
                    <?php if(!count($reviews)) echo '<b>'. $this->translate('Write a comment').'</b>'; ?>
                    <?php foreach($reviews as $review):?>
                        <li class="media">
                            <a href="#" class="float-left">
                                <img src="/img/users/avatar.png" alt="" class="rounded-circle">
                            </a>
                            <div class="media-body">
                        <span class="text-muted float-right">
                            <small class="text-muted"><?=\Sulde\Service\Common\Common::getTimeAgo($review->getCreatedDate())?></small>
                        </span>
                                <strong class="text-success"><?=$this->escapeHtml($review->getPeopleName())?></strong>
                                <p><?=$this->escapeHtml($review->getContent())?></p>
                            </div>
                        </li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
    </div>

    <form id="frmCommenPost" action="#" method="post">
        <a id="comment"></a>
        <div class="row">
            <div class="col-md-12 col-12 padding-bottom-5">
                <input type="hidden" name="hotelId" value="<?=$hotelId?>">
                <?php
                if($userInfo) $userFullName=$userInfo->getFullname();
                ?>
                <input type="text" id="commentName" name="name" value="<?=$userFullName;?>" class="form-control" placeholder="<?=$this->translate("Name");?>" data-container="body" data-toggle="popover" data-placement="top" data-content="<?=$this->translate('Please input your name.');?>" />
            </div>
            <div class="col-md-12 col-12">
                <textarea class="form-control" id="commentContent" name="comment" placeholder="<?=$this->translate('Write a comment...');?>" rows="3" data-container="body" data-toggle="popover" data-placement="top" data-content="<?=$this->translate('Please input content.');?>"></textarea>
            </div>
            <div class="col-md-12 col-12">
                <div class="starrating risingstar d-flex justify-content-center flex-row-reverse" data-container="body" data-toggle="popover" data-placement="top" data-content="<?=$this->translate('Please choose to star.');?>">
                    <input type="radio" id="star5" name="rating" value="5" /><label class="fa fa-star" for="star5" title="5 star"></label>
                    <input type="radio" id="star4" name="rating" value="4" /><label class="fa fa-star" for="star4" title="4 star"></label>
                    <input type="radio" id="star3" name="rating" value="3" /><label class="fa fa-star" for="star3" title="3 star"></label>
                    <input type="radio" id="star2" name="rating" value="2" /><label class="fa fa-star" for="star2" title="2 star"></label>
                    <input type="radio" id="star1" name="rating" value="1" /><label class="fa fa-star" for="star1" title="1 star"></label>
                </div>
            </div>
            <div class="col-md-12 col-12">
                <button type="button" id="btnPostComment" class="btn btn-success">Đăng bình luận</button>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ready(function(){
        $( "#btnPostComment" ).click(function() {

            $('#commentName').popover('dispose');
            $('#commentContent').popover('dispose');
            $('#starrating').popover('dispose');

            if(!$('#commentName').val()){
                $('#commentName').popover('show');
                $('#commentName').focus();
                return;
            }else if(!$('#commentContent').val()){
                $('#commentContent').popover('show');
                $('#commentContent').focus();
                return;
            }else if(!$("input[name='rating']:checked"). val()){
                $('.starrating').popover('show');
                return;
            }

            var r= $('<span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>');
            $( "#btnPostComment" ).append(r);
            $( "#btnPostComment" ).attr("disabled", "disabled");

            $("#frmCommenPost").ajaxSubmit({
                url: '/guest-add-review.html',
                type: 'post',
                complete: function (xhr) {
                    response = xhr.responseJSON;
                    if(response.status==0){
                        alert(response.message);
                    }else{
                        var item = '<li class="media">\n' +
                            '                        <a href="#" class="float-left">\n' +
                            '                            <img src="/img/users/avatar.png" alt="" class="rounded-circle">\n' +
                            '                        </a>\n' +
                            '                        <div class="media-body">\n' +
                            '                            <span class="text-muted float-right">\n' +
                            '                                <small class="text-muted">1 second ago</small>\n' +
                            '                            </span>\n' +
                            '                            <strong class="text-success">'+$('#commentName').val()+'</strong>\n' +
                            '                            <p>\n' +$('#commentContent').val()+'</p>\n' +
                            '                        </div>\n' +
                            '                    </li>'

                        $( ".media-list" ).append(item);

                        uId='<?php if($userInfo) echo $userInfo->getId()?>';
                        if(!uId) $('#commentName').val('');
                        $('#commentContent').val('');
                        for (i=1;i<=5;i++) $('#star'+i).prop('checked', false);
                    }
                    $(".spinner-grow").remove();
                    $( "#btnPostComment" ).removeAttr("disabled", "disabled");
                }
            });
        });
    })
</script>